{ config, pkgs, modulesPath, inputs, outputs, ... }:
{
  imports = [
    # Autogenerated configuration specific to the iso, and not included in repo
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
    # ../../secrets
  ];

  environment.systemPackages = with pkgs; [
    
  ];

  extra-services.tailscale = {
    enable = true;
    lxc = true;
  };
  extra-services.host-checkin.enable = true;

  sops.secrets.cloudflare-api-token = {
    owner = "caddy";
    mode = "0400";
  };

  extra-services.caddy-proxy = {
    enable = true;
    cloudflareTokenFile = config.sops.secrets.cloudflare-api-token.path;
    
    services = {
      
      "stark.montycasa.net" = { 
        protocol = "https"; 
        upstream = "192.168.86.93:8006"; 
      };
      
      "starlord.montycasa.net" = { 
        protocol = "https"; 
        upstream = "192.168.86.95:8006"; 
      };

      "loki.montycasa.net" = { 
        protocol = "https"; 
        upstream = "192.168.86.97:8006"; 
      };

      "wakanda.montycasa.net" = { 
        protocol = "https"; 
        upstream = "100.122.26.79:8006"; 
      };

      "pbs.montycasa.net" = { 
        protocol = "https"; 
        upstream = "192.168.86.123:8007";
      };

      "truenas.montycasa.net" = { 
        protocol = "https"; 
        upstream = "192.168.86.99:443"; 
      };

      "bucky.montycasa.net" = { 
        protocol = "https"; 
        upstream = "100.118.191.95:443"; 
      };

      "uptime.montycasa.net" = { 
        protocol = "http"; 
        upstream = "192.168.86.106:3001"; 
      };

      "omada.montycasa.net" = { 
        protocol = "https"; 
        upstream = "192.168.86.135:8043"; 
      };

      "router.montycasa.net" = { 
        protocol = "http"; 
        upstream = "192.168.86.1:80"; 
      };
      
      "blocker.montycasa.net" = {
        protocol = "http"; 
        upstream = "192.168.86.1:3000"; 
      };
      
      "git.montycasa.net" = {
        protocol = "http";
        upstream = "192.168.86.120:3000";
      };

      "qbittorrent.montycasa.net" = { 
        protocol = "http"; 
        upstream = "192.168.86.114:8080"; 
      };

      "radarr.montycasa.net" = { 
        protocol = "http"; 
        upstream = "192.168.86.114:7878"; 
      };

      "sonarr.montycasa.net" = { 
        protocol = "http"; 
        upstream = "192.168.86.114:8989"; 
      };

      "bazarr.montycasa.net" = { 
        protocol = "http"; 
        upstream = "192.168.86.114:6767"; 
      };

      "prowlarr.montycasa.net" = { 
        protocol = "http"; 
        upstream = "192.168.86.114:9696"; 
      };
      
      "youtarr.montycasa.net" = { 
        protocol = "http"; 
        upstream = "192.168.86.114:3087"; 
      };

      # MinusPod is intentionally reachable through the local/Tailscale proxy only.
      "minuspod.montycasa.net" = {
        protocol = "http";
        upstream = "100.121.147.57:8000";
      };

      "frigate.montycasa.net" = { 
        protocol = "http"; 
        upstream = "192.168.86.116:5000"; 
      };

      "dockge.montycasa.net" = { 
        protocol = "http"; 
        upstream = "192.168.86.112:5001"; 
      };

      "homepage.montycasa.net" = { 
        protocol = "http"; 
        upstream = "192.168.86.118:8082"; 
      };

      "paperless.montycasa.net" = { 
        protocol = "http"; 
        upstream = "192.168.86.133:28981";
      };

      "myspeed.montycasa.net" = { 
        protocol = "http"; 
        upstream = "192.168.86.106:5216"; 
      };

      "grist.montycasa.net" = { 
        protocol = "http"; 
        upstream = "192.168.86.132:8484"; 
      };

      "syncthing.montycasa.net" = { 
        protocol = "http"; 
        upstream = "192.168.86.99:20910"; 
      };

      "search.montycasa.net" = {
        protocol = "http";
        upstream = "192.168.86.137:8080";
      };

      # Operator-confirmed LAN/Tailscale-only proxy; perimeter not independently live-verified.
      "hermes.montycasa.net" = {
        protocol = "http";
        upstream = "192.168.86.126:8787";
      };

      # Mercury's HTTPS entry point for the Hermes dashboard. The dashboard
      # listener is restricted to tailscale0, so keep the proxy upstream on
      # the Hermes host's Tailscale address rather than its LAN address.
      "hermes-dashboard.montycasa.net" = {
        protocol = "http";
        upstream = "100.81.254.49:9119";
      };

      # OpenCode v2 web UI. The server listens only on Hermes' Tailscale
      # address, so the upstream is its Tailscale IP, never the LAN address.
      # OpenCode's own server password stays enforced; Caddy adds only TLS.
      "opencode.montycasa.net" = {
        protocol = "http";
        upstream = "100.81.254.49:4096";
      };

      # Pi-hole admin/API web UIs — Gate 3B. local-proxy is reachable only
      # from the LAN and Tailscale; it proxies to LAN-only Pi-hole Web at
      # port 8080. Both Pi-holes use the SOPS-rendered API credential
      # (pihole-api-password) and serve the same reviewed Nix policy.
      "pihole1.montycasa.net" = {
        protocol = "http";
        upstream = "192.168.86.101:8080";
      };

      "pihole2.montycasa.net" = {
        protocol = "http";
        upstream = "192.168.86.102:8080";
      };
    };

    sshUpstream = "192.168.86.120:22";
  };

  networking.firewall = {
    checkReversePath = "loose";
  };
  
  services.openssh.enable = true;  

  system.stateVersion = "25.05";
}
